config/routes.rb
Rails.application.routes.draw do
  devise_for :users 
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'home#index'
  resources :contact_us, only: [:new, :create]
  get 'contact_us/thank_you', to: 'contact_us#thank_you'
  get 'about_us', to: 'about_us#index'
  get 'wikipedia_search', to: 'wikipedia_search#index'
  resources :notes do 
    member do
      get 'download'
    end
  end

  devise_scope :user do  
    get '/users/sign_out' => 'devise/sessions#destroy'     
 end
 
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
  def self.ransackable_attributes(auth_object = nil)
    authorizable_ransackable_attributes
  end
  def self.ransackable_associations(auth_object = nil)
      authorizable_ransackable_associations
  end
end

app/models/contact_us.rb
class ContactUs < ApplicationRecord
  validates :name, presence: true, length: { maximum: 255 }
  validates :email, presence: true
  validate :valid_email_format
  validates :number, presence: true, length: { minimum: 10, maximum: 15 }
  validates :message, presence: true, length: { minimum: 10 }

  before_save :sanitize_email

  private

  def sanitize_email
    self.email = email.downcase.strip
  end

  def valid_email_format
    unless /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.match?(email)
      errors.add(:email, "is not in a valid format")
    end
  end
end

app/models/note.rb
class Note < ApplicationRecord
    has_one_attached :pdf_file
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/about_us_controller.rb
class AboutUsController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contact_us_controller.rb
# app/controllers/contact_us_controller.rb
class ContactUsController < ApplicationController
    def new
      @contact = ContactUs.new
    end
  
    def create
      @contact = ContactUs.new(contact_params)
      if @contact.save
        flash[:success] = 'Message sent successfully!'
        redirect_to contact_us_thank_you_path
      else
        render :new
      end
    end
    private
  
    def contact_params
      params.require(:contact_us).permit(:name, :email, :number, :message)
    end
  end
  

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
      def new
        @note = Note.new
      end
    
      def create
        @note = Note.new(note_params)
        if @note.save
          redirect_to notes_path, notice: 'Note created successfully.'
        else
          render :new
        end
      end
    
      def index
        @notes = Note.all
      end

      def download
        @note = Note.find(params[:id])
        
        if @note.pdf_file.attached?
          send_data @note.pdf_file.download, filename: @note.pdf_file.filename.to_s, type: @note.pdf_file.content_type
        else
          send_data @note.content, filename: "#{note.title}.txt", type: 'text/plain'
        end
      end

      private
      def note_params
        params.require(:note).permit(:title, :content,:pdf_file)
      end
end

app/controllers/wikipedia_search_controller.rb
class WikipediaSearchController < ApplicationController
  def index
    if params[:query]
      @query = params[:query]
      @results = search_wikipedia(@query)
    end
  end

  private

  def search_wikipedia(query)
    # debugger
    response = RestClient.get 'https://en.wikipedia.org/w/api.php', params: {
      action: 'query',
      format: 'json',
      list: 'search',
      srsearch: query 
    }

    data = JSON.parse(response.body)
    data['query']['search']
  end
end

app/helpers/about_us_helper.rb
module AboutUsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
    def render_error_messages(model, attribute)
      if model.errors[attribute].any?
        content_tag(:div, model.errors[attribute].to_sentence, class: 'text-danger')
      end
    end
end

app/helpers/contact_us_helper.rb
module ContactUsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/wikipedia_search_helper.rb
module WikipediaSearchHelper
end

app/views/about_us/index.html.erb
<!-- app/views/about_us/index.html.erb -->
<div class="container mt-5">
  <div class="row">
    <div class="col-md-8 offset-md-2">

      <h1 class="display-4 mb-4 text-center" style="color: #ff0000;">About Us</h1>

      <p class="lead text-center" style="color: #0066cc;">Welcome to AmitCoaching!</p>

      <p style="color: #333333;">At AmitCoaching, we are driven by a passion for Our mission is to empower individuals by providing accessible and high-quality education, fostering a lifelong love for learning and enabling them to reach their full potential in a rapidly changing world. Our journey began with the vision to Our founders established AmitCoaching with the goal of creating a sustainable and socially responsible business. Our guiding principles include environmental stewardship, ethical business practices, and a commitment to giving back to the community.</p>

      <h2 class="mt-4" style="color: #0066cc;">Our Mission:</h2>
      <p style="color: #333333;">Our mission is to empower individuals by providing accessible and high-quality education, fostering a lifelong love for learning and enabling them to reach their full potential in a rapidly changing world.</p>
      <h2 style="color: #0066cc;">What Sets Us Apart:</h2>
      <p style="color: #333333;">One of our key differentiators is our unwavering commitment to using sustainable materials. We carefully source recycled and upcycled materials to create our handmade crafts, minimizing environmental impact and contributing to a circular economy.</p>

      <h2 style="color: #0066cc;">Community Engagement:</h2>
      <p style="color: #333333;">We regularly organize free workshops and seminars open to the community. These events cover a range of topics, from study skills and career guidance to technology and innovation, empowering individuals with valuable knowledge and skills.</p>

      <h2 style="color: #0066cc;">Future Goals:</h2>
      <p style="color: #333333;"><strong>Aspiration: </strong> To become a globally recognized and influential player in the education sector.,<br> <strong>Goals:</strong>Expand our educational offerings to cater to a diverse global audience.</p>


      <p style="color: #333333;">Thank you for being a part of our journey. We look forward to continuing to serve and make a positive impact in Education field.</p>

      <div class="card" style="width: 18rem;">
            <%= image_tag 'amit.jpeg', class: 'card-img-top', alt: 'Amit' %>
            <div class="card-body">
                <h5 class="card-title"><strong>Name:</strong> Amit Singh Tomar</h5>
                <p class="card-text"><strong>Education:</strong>- Master:Master of Science(Math), Graduation: Bachelor of Science(Computer Science)</p>
                <h2>Subscribe my Youtube Channel</h2>
                <a href="https://www.youtube.com/@amitsircoachingclasses" class="btn btn-primary" style="color: red;">
                  <img src="assets/youtube" alt="YouTube Logo" style="width: 20px; height: 20px; margin-right: 5px;"> Watch on YouTube
                </a> 
            </div>
       </div>

      <p style="color: #888888;" class="mt-4">AmitSirCoaching - 2023</p>

    </div>
  </div>
</div>

app/views/contact_us/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Contact Us</title>
    <style>
        form {
            max-width: 400px;
            width: 100%;
            padding: 20px;
            background-color: #fff;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
            border-radius: 8px;
            text-align: left;
        }

        label {
            display: block;
            margin-bottom: 8px;
        }

        input,
        textarea {
            width: 100%;
            padding: 8px;
            margin-bottom: 16px;
            border: 1px solid #ccc;
            border-radius: 4px;
            box-sizing: border-box;
        }

        button {
            background-color: #4caf50;
            color: #fff;
            padding: 10px 15px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
        }
    </style>
</head>
<body>
        <% flash.each do |key, value| %>
        <div class="flash <%= key %>"><%= value %></div>
        <% end %>

        <%= form_with(model: @contact, url: contact_us_create_path, local: true) do |form| %>
        <div>
            <%= form.label :name %>
            <%= form.text_field :name, required: true %>
        </div>

        <div>
            <%= form.label :email %>
            <%= form.email_field :email, required: true %>
        </div>

        <div>
            <%= form.label :number %>
            <%= form.text_field :number, required: true %>
        </div>

        <div>
            <%= form.label :message %>
            <%= form.text_area :message, required: true %>
        </div>

        <div>
            <%= form.submit 'Submit' %>
        </div>
        <% end %>


</body>
</html>

app/views/contact_us/new.html.erb
<!-- app/views/contact_us/new.html.erb -->
<div class="container mt-5">
  <h1>Contact Us</h1>

  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %> alert-dismissible fade show" role="alert">
      <%= value %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %>

  <%= form_with(model: @contact, url: contact_us_path, local: true, html: { class: 'mb-4' }) do |form| %>
    <div class="mb-3">
      <%= form.label :name, class: 'form-label' %>
      <%= form.text_field :name, required: true, class: 'form-control' %>
      <%= render_error_messages(@contact, :name) %>
    </div>

    <div class="mb-3">
      <%= form.label :email, class: 'form-label' %>
      <%= form.email_field :email, required: true, class: 'form-control' %>
      <%= render_error_messages(@contact, :email) %>
    </div>

    <div class="mb-3">
      <%= form.label :number, class: 'form-label' %>
      <%= form.text_field :number, required: true, class: 'form-control' %>
      <%= render_error_messages(@contact, :number) %>
    </div>

    <div class="mb-3">
      <%= form.label :message, class: 'form-label' %>
      <%= form.text_area :message, required: true, class: 'form-control', rows: 4 %>
      <%= render_error_messages(@contact, :message) %>
    </div>

    <div>
      <%= form.submit 'Submit', class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>

app/views/contact_us/thank_you.html.erb
<div class="container mt-5">
  <h1>Thank You!</h1>
  <p class="lead">Your message has been sent successfully. We will get back to you soon.</p>

  <div class="mt-4">
    <%= link_to 'Back to Home', root_path, class: 'btn btn-primary' %>
  </div>
</div>

app/views/home/index.html.erb
<style>
        .marquee-container {
            overflow: hidden;
            white-space: nowrap;
            margin: 20px 0;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1); 
            border-radius: 8px; 

        
            /* position: absolute; */
        }

        .marquee-container img {
            width: 100%; 
            height: 450px; 
            display: block; 
        }
        section {
            max-width: 800px;
            text-align: center;
            margin: 20px;
            padding: 20px;
            background-color: #fff;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
            border-radius: 8px;
        }

        h2 {
            color: #333;
            margin-bottom: 10px;
        }

        p {
            font-size: 16px;
            line-height: 1.6;
            color: #555;
        }

        .image-description {
        overflow: hidden;
        white-space: nowrap;
        margin: 20px 0;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        border-radius: 8px;
        max-width: 100%;
    }

    .image-description img {
        width: 100%;
        height: 400px;
        display: block;
        border-radius: 8px 8px 0 0; 
    }

    .opening-announcement {
        padding: 20px;
    }

    @media only screen and (max-width: 600px) {
        .opening-announcement {
            padding: 10px;
        }
    }

</style>

<div class="marquee-container" >
    <%= image_tag "home1.jpg" %>  
</div>

<br>
<br>

<div class="image-description">
    <%= image_tag "amitcoaching.jpeg" %>
    <div class="opening-announcement" style="color: black;background-color: white;">
        <h2>🌟 Exciting News! 🌟</h2>
        <p>We are thrilled to announce the grand opening of our brand new coaching center! 🎉</p>

        <h3>📚 Unlock Your Potential with AmitCoaching 📚</h3>
        <p>Embark on a journey of knowledge, growth, and success. Our dedicated team of educators is committed to providing top-notch guidance and support to help you achieve your goals.</p>

        <p><strong>🏫 Location:</strong> Near Madhav Excellence School Ater Road Porsa<br>
        <strong>📆 Opening Date:</strong> 01/02/2024<br>

        <p>Come and discover a learning environment designed to inspire, motivate, and empower. Whether you're preparing for exams, enhancing your skills, or pursuing a passion, we've got you covered.</p>

        <p><strong>🌐 Our Offerings:</strong></p>
        <ul>
            <li>Navodaya,Sainik</li>
            <li>Personalized Coaching</li>
            <li>State-of-the-Art Facilities</li>
        </ul>

        <p><strong>👩‍🏫 Meet Our Experienced Instructors:</strong></p>
        <ul>
            <li>Amit Singh Tomar </li>
        </ul>

        <p>Don't miss the chance to be part of this educational journey. We look forward to welcoming you to [Your Coaching Center Name]!</p>

        <p>For inquiries and registration, contact us at:</p>
        <p><strong>📞 Phone:</strong> 8349902861<br>

        <p>Get ready to elevate your learning experience! 🚀</p>

        <p># AmitCoaching #GrandOpening #EducationForAll</p>
    </div>
</div>


<section>
    <h2>About Us</h2>
    <p>
        AmitCoaching is dedicated to helping you achieve your goals and unlock your full potential. Our experienced coaches are here to guide and support you on your journey to success.
    </p>
</section>

<section>
    <h2>What We Believe in</h2>
    <blockquote>
        <strong>"AmitCoaching has truly transformed my life. The personalized guidance and support have been instrumental in my personal and professional growth."</strong>
    </blockquote>
    <p id="basic" style="color: #333;">
        At AmitCoaching, we firmly believe in the power of personalized guidance and support. Our commitment is to empower individuals on their journey towards personal and professional growth. The transformative experiences shared by our clients reflect the core values we uphold — a dedication to fostering positive change and unlocking the full potential within each individual. Through tailored coaching, we strive to make a meaningful impact on lives, helping our clients achieve their goals and navigate towards success.
    </p>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AmitCoaching</title>
    <meta name="viewport" content="width=device-width, initial-scale=1,shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <style>
      .navbar-nav .nav-link {
        text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.8);
        color: light-grey;
      }
      #footer {
        font-size: 34px;
        font-style: Times New Roman;
        margin: 0;
        text-align: center;
        color: darkblue;
    }
      .navbar-brand img {
        width: 85px;
        height: auto;
        margin-right: 10px;
        border-radius: 25px
    }
    body {
            font-family: 'Arial', sans-serif;
            background-color: #F8F8F8;
            color: #333;
            margin: 0;
            padding: 0;
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
            background-image: url(<%= asset_path('bg1.jpg') %>);
        }
    </style>
  </head>
  <body>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
          <a class="navbar-brand" href="/">
            <%= image_tag "home2.jpg", width: 85 %>
            <span>AmitCoaching</span>
          </a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
          <div class="collapse navbar-collapse " id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <%= link_to 'Home', root_path, class: 'nav-link' %>
              </li>
              <li class="nav-item">
                <%= link_to 'Contact Us', new_contact_u_path, class: 'nav-link' %>
              </li>
              <li class="nav-item">
                <%= link_to 'About Us', about_us_path, class: 'nav-link' %>
              </li>
              <li class="nav-item">
                <%= link_to 'Wikipedia Search', wikipedia_search_path, class: 'nav-link' %>
              </li>
              <li class="nav-item">
                <%= link_to 'Notes', notes_path, class: 'nav-link' %>
              </li>
              <% if user_signed_in? %>
                <li class="nav-item">
                <%= link_to "exit", destroy_user_session_path, method: :delete , class: 'nav-link' %>
                </li>
              <% else %>
                <li class="nav-item">
                  <%= link_to 'Login', new_user_session_path, class: 'nav-link' %>
                </li>
                <li class="nav-item">
                  <%= link_to 'Sign Up', new_user_registration_path, class: 'nav-link' %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    <%= yield %>
    <p id="footer" >&copy; 2024 AmitCoaching. All rights reserved.</p>
  </body>
</html>

app/views/notes/_note.html.erb
<!-- app/views/notes/_note.html.erb -->
<div class="note">
  <h3><%= note.title %></h3>
  <p><%= note.content %></p>
  <%= link_to 'Download', download_note_path(note), class: 'btn btn-secondary' %>
</div>

app/views/notes/index.html.erb
<div class="container">
  <h1 class="mt-4 mb-4">Notes</h1>

  <% @notes.each do |note| %>
    <div class="card mb-4">
      <div class="card-body">
        <h3 class="card-title"><%= note.title %></h3>
        <p class="card-text"><%= note.content %></p>

        <% if note.pdf_file.attached? %>
          <div class="mb-3">
            <embed src="<%= url_for(note.pdf_file) %>" type="application/pdf" width="100%" height="500px" />
          </div>
          <%= link_to 'Download PDF', url_for(note.pdf_file), class: 'btn btn-secondary mb-2', target: '_blank' %>
        <% end %>

        <%= link_to 'Download Content', download_note_path(note), class: 'btn btn-primary' %>
      </div>
    </div>
  <% end %>

</div>

app/views/wikipedia_search/index.html.erb
<div class="container">
  <h1>Wikipedia Search</h1>

  <%= form_tag(wikipedia_search_path, method: :get, class: "search-form") do %>
    <%= label_tag :query, 'Enter search term:' %>
    <%= text_field_tag :query, params[:query], class: "search-input" %>
    <%= submit_tag 'Search', class: "search-button" %>
  <% end %>

  <% if @query %>
    <h2>Search Results for "<%= @query %>"</h2>
    <% if @results.any? %>
      <ul class="search-results">
        <% @results.each do |result| %>
          <li>
            <h3><%= link_to result['title'], "https://en.wikipedia.org/wiki/#{result['title']}", target: "_blank" %></h3>
            <p><%= simple_format(result['snippet']) %></p> 
          </li>
        <% end %>
      </ul>
    <% else %>
      <p>No results found for "<%= @query %>"</p>
    <% end %>
  <% end %>
</div>